---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-display-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-display-app
  template:
    metadata:
      labels:
        app: todo-display-app
    spec:
      containers:
      - name: todo-display
        image: sohanmer/todo-display:latest
        ports:
        - containerPort: 3200
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://<BACKEND_IP>:3000/get-tasks

---
apiVersion: v1
kind: Service
metadata:
  name: todo-display-service
spec:
  selector:
    app: todo-display-app
  ports:
  - protocol: TCP
    port: 3200
    targetPort: 3200
  type: LoadBalancer
