---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-frontend-app
  template:
    metadata:
      labels:
        app: todo-frontend-app
    spec:
      containers:
      - name: todo-frontend
        image: <username>/todo-frontend:latest
        ports:
        - containerPort: 3100
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://<BACKEND_IP>:3000/create-task

---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  selector:
    app: todo-frontend-app
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
  type: LoadBalancer
